- id: '1535560519137'
  alias: Lights at sunset
  trigger:
  - event: sunset
    offset: -01:00:00
    platform: sun
  condition: []
  action:
  - data:
      brightness_pct: '30'
      entity_id:
      - light.hallway_light
      - light.living_room_window
      - light.switch_light
    service: light.turn_on
- id: '1535561377167'
  alias: Auto turn off lights
  trigger:
  - at: '23:00'
    platform: time
  - event: sunrise
    offset: 01:00:00
    platform: sun
  condition: []
  action:
  - alias: ''
    data:
      entity_id:
      - light.living_room_window
      - light.hallway_light
    service: light.turn_off
  - data:
      entity_id: light.switch_light
    service: light.turn_off
- id: '1540238502789'
  alias: 'Lights in the morning '
  trigger:
  - at: 06:00
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data:
      brightness_pct: '30'
      entity_id: light.hallway_light
      transition: '20'
    service: light.turn_on
  - data:
      brightness_pct: '30'
      entity_id: light.living_room_window
      transition: '20'
    service: light.turn_on
- id: '1542232622410'
  alias: Trigger radio
  trigger:
  - at: '12:29'
    platform: time
  condition: []
  action:
  - data: {}
    service: script.1545863420408
