
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 5

# Text to speech
tts:
  - platform: google_translate

automation: !include_dir_merge_list automation/
script: !include scripts.yaml
scene: !include scenes.yaml
light: !include lights.yaml

google_assistant:
  project_id: home-assistant-94b3b
  exposed_domains:
          - light
          - script

lovelace:
  mode: yaml
  
  resources:
  - url: /hacsfiles/vacuum-card/vacuum-card.js
    type: module

sensor:
  - platform: vasttrafik
    key: !secret vasttrafik_key
    secret: !secret vasttrafik_secret
    departures:
      - from: "Kungälvs resecentrum väst"
        heading : "Volvo Torslanda PV"
        name: "To work"
      - from: "Kungälvs resecentrum"
        heading: "Nordstan"
        name: "To Göteborg"
  - platform: time_date
    display_options:
            - 'time'
            - 'date'
            - 'date_time'
  - platform: mqtt
    state_topic: "home/phone_alarm_time"
    name: phone_alarm_time
    icon: mdi:alarm
    qos: 1
  - platform: mqtt
    state_topic: "nodemcu/temp"
    name: Temperature
    icon: mdi:thermometer
    qos: 0
    expire_after: 125
    unique_id: temperature
  - platform: mqtt
    state_topic: "nodemcu/pressure"
    name: Pressure
    icon: mdi:gauge
    qos: 0
    expire_after: 125
    unique_id: pressure

media_player:
  - platform: androidtv
    host: 192.168.0.105
    name: philips_androidtv
    adb_server_ip: 127.0.0.1
    adb_server_port: 5037


spotify:
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret

vacuum:
  - platform: xiaomi_miio
    host: !secret vacuum_ip
    token: !secret vacuum_token

hacs:
    token: !secret hacs_token

# Zones
zone:
  - name: Volvo Cars
    latitude: 57.729676
    longitude: 11.857164
    radius: 500
    icon: mdi:factory
