
# Loads default set of integrations. Do not remove.
default_config:

http:
  ip_ban_enabled: true
  login_attempts_threshold: !secret failure_to_ban
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret ip_proxy

input_datetime:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml
light: !include lights.yaml
lovelace:
  !include lovelace_config.yaml
mqtt: !include mqtt.yaml

monitor_docker: !include monitor_docker.yaml

google_assistant:
  project_id: !secret project_id
  service_account: !include SERVICE_ACCOUNT.json
  report_state: true
  exposed_domains:
    - light

input_text:
  helper_last_controller_event:
    name: Helper - Last Controller Event
    initial: temp
