# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

http:
   ip_ban_enabled: true
   login_attempts_threshold: !secret ip_ban_threshold
   use_x_forwarded_for: true
   trusted_proxies:
      - !secret trusted_proxy_ip

lovelace:
   mode: yaml
   resources:
     - url: /hacsfiles/vacuum-card/vacuum-card.js
       type: module
     - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
       type: module

frontend:
  themes: !include_dir_merge_named themes

mobile_app:

person:
  - name: Erik
    id: erik
    user_id: !secret erik_user_id
    device_trackers:
      - device_tracker.eriks_phone
      - device_tracker.eriks_galaxy_s9
  - name: Elin
    id: elin
    user_id: !secret elin_user_id
    device_trackers:
      - device_tracker.elins_iphone
      - device_tracker.elins_iphone_wifi

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include_dir_merge_list automation/
script: !include scripts.yaml
scene: !include scenes.yaml
light: !include lights.yaml
zone: !include zones.yaml
sensor: !include sensor.yaml

google_assistant:
   project_id: !secret google_assistant_project_id
   service_account: !include Home-assistant-docker-a6ed3f94ed6d.json
   report_state: true
   expose_by_default: true
   exposed_domains:
      - switch
      - light

spotify:
   client_id: !secret spotify_client_id
   client_secret: !secret spotify_client_secret

vacuum:
   - platform: xiaomi_miio
     host: !secret vacuum_ip
     token: !secret vacuum_token

media_player:
  - platform: androidtv
    name: Philips android TV
    host: !secret philips_tv_ip
    screencap: false
  - platform: androidtv
    name: Bedroom android TV
    host: !secret bedroom_tv_ip
    screencap: false

camera:
  - platform: local_file
    file_path: !secret file_path

sonoff:
    username: !secret sonoff_username
    password: !secret sonoff_password
