
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

http:
  base_url: !secret base_url_input
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 5

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

google_assistant:
  project_id: home-assistant-94b3b
  api_key: !secret google_api_key 
  exposed_domains:
          - light
          - script

lovelace:
  mode: yaml

sensor:
#  - platform: vasttrafik
#    key: !secret vasttrafik_key
#    secret: !secret vasttrafik_secret
#    departures:
#      - from:
#        heading :
  - platform: time_date
    display_options:
            - 'time'
            - 'date'
            - 'date_time'
  - platform: mqtt
    state_topic: "home/phone_alarm_time"
    name: phone_alarm_time
    icon: mdi:alarm
    qos: 1

media_player:
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret
  - platform: androidtv
    host: 192.168.0.105
    name: philips_androidtv
    adb_server_ip: 127.0.0.1
    device_class: androidtv
