# Groups
- platform: group
  name: "Upstairs living room ceiling"
  entities:
    - light.upstairs_living_room_1
    - light.upstairs_living_room_2
    - light.upstairs_living_room_3

- platform: group
  name: Living room window advent
  entities:
    - light.living_room_window
    - light.living_room_window_2

- platform: group
  name: Advent lights
  entities:
    - light.living_room_window_advent
    - light.office_window_advent
    - light.living_room_window_star
    - light.kitchen_window_star

# Switich as light
- platform: switch
  name: Upstairs living room corner
  entity_id: switch.upstairs_living_room_corner

