- platform: switch
  name: Dresser
  entity_id: switch.ikea_switch

- platform: group
  name: Living room lights
  entities:
    - light.living_room_window_right
    - light.living_room_window_left

- platform: group
  name: Entrance lights
  entities:
    - light.entrance_1
    - light.entrance_2
    - light.entrance_3

- platform: group
  name: Extra bedroom lights
  entities:
    - light.extra_bedroom_window
    - light.dresser

- platform: group
  name: Bedroom lights
  entities:
    - light.bedroom_roof
    - light.bedroom_window

