- platform: switch
  name: Kitchen bench left
  entity_id: switch.sonoff_kitchen_1

- platform: switch
  name: Kitchen bench right
  entity_id: switch.sonoff_kitchen_2

- platform: switch
  name: Kitchen drink
  entity_id: switch.ikea_switch

- platform: group
  name: Living room lights
  entities:
    - light.living_room_window_right
    - light.living_room_window_left
    - light.living_room_advent

- platform: group
  name: Entrance lights
  entities:
    - light.entrance_1
    - light.entrance_2
    - light.entrance_3

- platform: group
  name: Office lights
  entities:
    - light.office_window
    - light.office_advent

- platform: group
  name: Bedroom lights
  entities:
    - light.bedroom_roof
    - light.bedroom_window
    - light.bedroom_advent

- platform: group
  name: Kitchen bench lights
  entities:
    - light.kitchen_bench_left
    - light.kitchen_bench_right

- platform: group
  name: Extra bedroom lights
  entities:
    - light.advent_star
 
################ Christmas ##################
- platform: switch
  name: Living room advent
  entity_id: switch.living_room_switch

- platform: switch
  name: Office advent
  entity_id: switch.office_switch

- platform: switch
  name: Bedroom advent
  entity_id: switch.bedroom_switch


