- platform: template
  sensors:
    vacuum_filter_left_hours:
      value_template: >
        {{ ((states('sensor.xiaomi_vacuum_cleaner_filter_left')| int) / 3600) | int  }}
    vacuum_main_brush_left_hours:
      value_template: >
        {{ ((states('sensor.xiaomi_vacuum_cleaner_main_brush_left')| int) / 3600) | int }}
    vacuum_side_brush_left_hours:
      value_template: >
        {{ ((states('sensor.xiaomi_vacuum_cleaner_side_brush_left')| int) / 3600) | int }}
    vacuum_sensor_dirty_left_hours:
      value_template: >
        {{ ((states('sensor.xiaomi_vacuum_cleaner_sensor_dirty_left')| int) / 3600) | int }}
    vacuum_last_clean_duration_minutes:
      value_template: >
        {{ ((states('sensor.xiaomi_vacuum_cleaner_last_clean_duration')| int) / 60) | int }}
