title: My home

views:
  - title: Start
    cards:
      # Sensors
      - type: markdown
        title: "Sensors"
        content: " "
      - type: sensor
        entity: sensor.indoor_temperature
        graph: line
        unit: °C
        detail: 1
        hours_to_show: 48
      - type: sensor
        entity: sensor.indoor_pressure
        graph: line
        unit: hPa
        detail: 1
        hours_to_show: 48

        # Lights
      - type: vertical-stack
        cards:
          - type: markdown
            title: "Lights"
            content: " "
          - type: horizontal-stack
            cards:
              - type: light
                entity: light.living_room_lights
              - type: light
                entity: light.entrance_lights
          - type: horizontal-stack
            cards:
              - type: light
                entity: light.office_window
              - type: light
                entity: light.extra_room_lights
          - type: horizontal-stack
            cards:
              - type: light
                entity: light.bedroom_lights
 
        # Spotify
      - type: media-control
        entity: media_player.spotify
 # Automations
  - title: Automation control
    cards:
      - type: entity-filter
        entities:
           - automation.auto_turn_off_lights
           - automation.button_toggle_lights
           - automation.lights_at_sunset
           - automation.lights_in_the_morning
           - automation.trigger_radio
           - automation.tv_paused
           - automation.tv_playing
           - automation.wakeup_lights
        state_filter:
           - "on"
           - "off"
  # Lights
  - title: Lights
    cards:
      - type: vertical-stack
        cards:
           - type: horizontal-stack
             cards:
                - type: light
                  entity: light.living_room_window_left
                - type: light
                  entity: light.living_room_window_right
           - type: horizontal-stack
             cards:
                - type: light
                  entity: light.dresser
                - type: light
                  entity: light.office_window
           - type: horizontal-stack
             cards:
                - type: light
                  entity: light.bedroom_roof
                - type: light
                  entity: light.bedroom_window

