- id: '1730231423123'
  alias: xiaomi button
  trigger:
  - platform: event
    event_type: state_changed
    event_data:
      entity_id: event.mii_button_action
  condition:
    - condition: template
      value_template: >
        {{ state_attr('event.mii_button_action', 'event_type') == 'single' }}
  action:
  - action: light.toggle
    target:
      entity_id:
        - light.upstairs_living_room_ceiling

- alias: Kids room right light on
  trigger:
  - platform: state
    entity_id: event.ikea_on_off_button_1_action
    attribute: event_type
    to: "on"
  condition: []
  action:
  - action: light.turn_on
    target:
      entity_id: light.kids_room_right_bed

- alias: Kids room right light off
  trigger:
  - platform: state
    entity_id: event.ikea_on_off_button_1_action
    attribute: event_type
    to: "off"
  condition: []
  action:
  - action: light.turn_off
    target:
      entity_id: light.kids_room_right_bed

- alias: Kids room left light on
  trigger:
  - platform: state
    entity_id: event.ikea_on_off_button_2_action
    attribute: event_type
    to: "on"
  condition: []
  action:
  - action: light.turn_on
    target:
      entity_id: light.kids_room_left_bed

- alias: Kids room left light off
  trigger:
  - platform: state
    entity_id: event.ikea_on_off_button_2_action
    attribute: event_type
    to: "off"
  condition: []
  action:
  - action: light.turn_off
    target:
      entity_id: light.kids_room_left_bed

- id: '1756239707149'
  alias: Tv room dimmer switch
  description: ''
  use_blueprint:
    path: EPMatt/philips_929002398602.yaml
    input:
      controller_device: 958ed90b8cfcb40b6596311b1b465182
      integration: Zigbee2MQTT
      helper_last_controller_event: input_text.helper_last_controller_event
- id: '1756240204781'
  alias: Tv room light dimmer
  description: ''
  use_blueprint:
    path: EPMatt/light.yaml
    input:
      controller_device: 958ed90b8cfcb40b6596311b1b465182
      controller_model: Philips 929002398602 Hue Dimmer switch v2
      light: light.tv_room
