- alias: Auto turn off lights
  trigger:
  - at: '23:00'
    platform: time
  - event: sunrise
    offset: 01:00:00
    platform: sun
  condition: []
  action:
    service: script.turn_on
    target:
      entity_id: script.all_lights_out

- alias: Lights at sunset
  trigger:
  - event: sunset
    offset: -01:00:00
    platform: sun
  condition: []
  action:
  - data:
      brightness_pct: '30'
      entity_id:
        - light.living_room_lights
        - light.bedroom_window
        - light.extra_bedroom_lights
        - light.office_window
        - light.bedroom_advent
    service: light.turn_on

- alias: 'Lights in the morning'
  trigger:
  - at: 05:30
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data:
      brightness_pct: '30'
      entity_id:
        - light.living_room_lights
        - light.extra_bedroom_lights
        - light.office_window
    service: light.turn_on

- alias: Trigger radio
  trigger:
    platform: template
    value_template: "{{ strptime(states('sensor.phone_alarm_time'), '%Y-%m-%d %H:%M') == strptime(states('sensor.date_time'), '%Y-%m-%d, %H:%M') }}"
  condition: []
  action:
  - data: {}
    service: script.start_radio_in_bedroom

- alias: Wakeup lights
  trigger:
    platform: template
    value_template: "{{ ((as_timestamp(strptime(states('sensor.phone_alarm_time'), '%Y-%m-%d %H:%M')) - 20*60) | timestamp_custom('%Y-%m-%d, %H:%M')) == strptime(states('sensor.date_time'), '%Y-%m-%d %H:%M') }}"
  action:
  - data:
      brightness_pct: '99'
      entity_id: light.wakeup
      transition: '1200'
    service: light.turn_on

- alias: TV paused
  trigger:
    - platform: state
      entity_id: 'media_player.living_room_tv'
      from: 'playing'
      to: 'paused'
  action:
      service: scene.turn_on
      entity_id: scene.livingroom_normal

- alias: TV playing
  trigger:
    - platform: state
      entity_id: 'media_player.living_room_tv'
      from: 'paused'
      to: 'playing'
  action:
      service: scene.turn_on
      entity_id: scene.livingroom_dim

- alias: Entrance motion activate
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_occupancy
      to: 'on'
  action:
      service: scene.turn_on
      target:
         entity_id: scene.occupied_entrance

- alias: Entrance motion deactivate
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_occupancy
      to: 'off'
  action:
      service: scene.turn_on
      target:
         entity_id: scene.empty_entrance



