- alias: Turn on kitchen bench light
  trigger:
    - platform: state
      entity_id: sensor.kitchen_switch_click
      to: 'on'
  action:
      - service: light.turn_on
        data:
                entity_id: light.kitchen_bench_lights

- alias: Turn off kitchen bench light
  trigger:
    - platform: state
      entity_id: sensor.kitchen_switch_click
      to: 'off'
  action:
      - service: light.turn_off
        data:
                entity_id: light.kitchen_bench_lights

- alias: Turn on lights entrance
  trigger:
    - platform: state
      entity_id: sensor.entrance_switch_action
      to: 'toggle'
  action:
    - service: light.toggle
      data:
        entity_id: light.entrance_lights
  
- alias: Turn on extra bedroom light
  trigger:
    - platform: state
      entity_id: sensor.bedroom_switch_night_click
      to: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.advent_star
        brightness_pct: 1

- alias: Turn off extra bedroom light
  trigger:
    - platform: state
      entity_id: sensor.bedroom_switch_night_click
      to: 'off'
  action:
    - service: light.turn_off
      data:
        entity_id: light.advent_star


    
  
