- alias: Button toggle bedroom roof
  trigger:
    - platform: state
      entity_id: 'sensor.xiaomi_button'
      to: 'single'
  action:
    - service: light.toggle
      data:
         entity_id: light.bedroom_roof

- alias: Button toggle bedroom window
  trigger:
    - platform: state
      entity_id: 'sensor.xiaomi_button'
      to: 'double'
  action:
    - service: light.toggle
      data:
         entity_id: light.bedroom_window
