- alias: Button toggle bedroom roof
  trigger:
    - platform: state
      entity_id: 'sensor.xiaomi_button'
      to: 'single'
  action:
    - service: light.toggle
      data:
         entity_id: light.bedroom_roof

- alias: Button max ligth bedroom roof
  trigger:
    - platform: state
      entity_id: 'sensor.xiaomi_button'
      to: 'hold'
  condition:
    - and:
      - condition: state
        entity_id: light.bedroom_roof
        state: "on"
      - condition: numeric_state
        entity_id: light.bedroom_roof
        below: 14
  action:
    - service: light.turn_on
      data:
         entity_id: light.bedroom_roof
         brightness_pct: 100

- alias: Button dim ligth bedroom roof
  trigger:
    - platform: state
      entity_id: 'sensor.xiaomi_button'
      to: 'hold'
  condition:
    - and:
      - condition: state
        entity_id: light.bedroom_roof
        state: "on"
      - condition: numeric_state
        entity_id: light.bedroom_roof
        above: 241
  action:
    - service: light.turn_on
      data:
         entity_id: light.bedroom_roof
         brightness_pct: 4

- alias: Button toggle bedroom window
  trigger:
    - platform: state
      entity_id: 'sensor.xiaomi_button'
      to: 'double'
  action:
    - service: light.toggle
      data:
         entity_id: light.bedroom_window
