esphome:
  name: livingroom
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: COMHEM_89CF62
  password: qk2e9pep
  
  manual_ip:
    static_ip: 192.168.0.88
    gateway: 192.168.0.1
    subnet: 255.255.255.0


#  # Enable fallback hotspot (captive portal) in case wifi connection fails
#  ap:
#    ssid: "Livingroom Fallback Hotspot"
#    password: "DwXTPPWRCiHm"

#captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
#api:

ota:
